# Generated by Django 5.2.17 on 2026-10-03 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='output_channel',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='output_channel',
        ),
        migrations.AddField(
            model_name='lead',
            name='especialidade',
            field=models.CharField(blank=True, choices=[('Previdenciário', 'Previdenciário'), ('Consumidor', 'Consumidor'), ('Trabalhista', 'Trabalhista'), ('Fora de escopo', 'Fora de escopo')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='impacto',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='lead',
            name='interesse',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('depois', 'Depois')], max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='initial_state',
            field=models.CharField(default='apresentacao', help_text='question_id inicial enviado no primeiro contato.', max_length=80),
        ),
        migrations.AlterField(
            model_name='lead',
            name='demand',
            field=models.CharField(blank=True, help_text="Campo 'tema' do protocolo Axioma.", max_length=300),
        ),
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(help_text='question_id atual (apresentacao, nome, situacao, ... ou ENCERRADO_CLASSIFICADO).', max_length=80),
        ),
        migrations.AlterField(
            model_name='lead',
            name='temperature',
            field=models.CharField(blank=True, choices=[('Qualificado', 'Qualificado'), ('Quente', 'Quente'), ('Desconfiado', 'Desconfiado'), ('Remarketing', 'Remarketing'), ('Desqualificado', 'Desqualificado')], max_length=20),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(help_text='Ex.: apresentacao, empresa, nome, situacao, ainda_na_empresa, tipo_de_situacao, afetou_renda, equipe_avaliar_situacao, validar, encerramento, repetir.', max_length=80)),
                ('text', models.TextField(blank=True)),
                ('audio_asset', models.CharField(blank=True, help_text='Identificador do OGG/Opus pré-gravado, usado quando a entrada do contato for áudio.', max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('company', 'question_id'), name='unique_company_question'),
        ),
    ]
