# Generated by Django 5.2.17 on 2026-10-03 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

DEFAULT_AREAS = ["Previdenciário", "Consumidor", "Trabalhista", "Fora de escopo"]

def seed_default_areas(apps, schema_editor):
    """Preserva o comportamento atual: toda empresa já cadastrada ganha as
    mesmas 4 áreas que antes eram um choices fixo e global, pra não quebrar
    o roteiro/agente em produção no momento do deploy desta migration."""
    Company = apps.get_model("crm", "Company")
    Area = apps.get_model("crm", "Area")
    for company in Company.objects.all():
        for name in DEFAULT_AREAS:
            Area.objects.get_or_create(company=company, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_companyinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='especialidade',
            field=models.CharField(blank=True, help_text='Nome de uma Area cadastrada pela empresa; validado em services.apply_fields, não é mais um choices fixo.', max_length=80),
        ),
        migrations.CreateModel(
            name='AtendenteInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='crm.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordChangeRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_required', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='crm.company')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_company_area')],
            },
        ),
        migrations.RunPython(seed_default_areas, migrations.RunPython.noop),
    ]
