# Generated by Django 5.2.17 on 2026-10-03 20:02

import uuid
from django.db import migrations, models


def apagar_convites_pendentes(apps, schema_editor):
    """Convites são efêmeros (expiram em 15min, somem após uso) -- não há
    conversão razoável de id sequencial pra UUID, então limpa a tabela antes
    de trocar o tipo da PK. Nada se perde: no pior caso, a empresa reenvia o convite."""
    AtendenteInvite = apps.get_model("crm", "AtendenteInvite")
    AtendenteInvite.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_emailchangerequest_profile'),
    ]

    operations = [
        migrations.RunPython(apagar_convites_pendentes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='atendenteinvite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
