# Generated by Django 5.2.17 on 2026-10-03 20:46

import crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('crm', '0006_alter_atendenteinvite_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTokenExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(default=crm.models.default_token_expiry)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expiry', to='authtoken.token')),
            ],
        ),
    ]
