# Generated by Django 5.2.17 on 2026-10-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_agenttokenexpiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='desfecho',
            field=models.CharField(blank=True, choices=[('encerrado', 'Encerrado'), ('comprometido', 'Comprometido'), ('falha', 'Falha durante o atendimento')], help_text='Só setado ao despachar um atendimento humano (ver services.despachar_lead).', max_length=20),
        ),
    ]
