# Generated by Django 5.2.17 on 2026-10-04 00:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_lead_desfecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='obrigatorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='obrigatoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(help_text='Ex.: apresentacao, empresa, nome, situacao, ainda_na_empresa, tipo_de_situacao, afetou_renda, equipe_avaliar_situacao, demanda, validar, encerramento, repetir.', max_length=80),
        ),
        migrations.CreateModel(
            name='Variavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('peso', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaveis', to='crm.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='variavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='crm.variavel'),
        ),
        migrations.AddConstraint(
            model_name='variavel',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_variavel'),
        ),
    ]
