# Generated by Django 5.2.17 on 2026-10-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_seed_variaveis_e_obrigatorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
