# Generated by Django 5.2.17 on 2026-10-04 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_companyinfo_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['ordem', 'id']},
        ),
        migrations.AddField(
            model_name='question',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Posição no fluxo de perguntas, definida por arrastar-e-soltar na tela Roteiro; sem efeito nos textos fora do fluxo.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='variavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='crm.variavel'),
        ),
    ]
