# Generated by Django 5.2.17 on 2026-10-04 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_seed_textos_fora_do_fluxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='variaveis_roteiro',
            field=models.JSONField(blank=True, default=dict, help_text='slug->texto coletado nas perguntas com Variável de roteiro customizada (ver services.apply_fields/render_text). Os 3 builtin (nome/especialidade/tema) não usam isto -- já são campos próprios do Lead.'),
        ),
        migrations.CreateModel(
            name='VariavelRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.CharField(help_text='Token usado como {slug} no texto; gerado a partir do nome, só letras minúsculas e _.', max_length=80)),
                ('cor', models.CharField(default='#D97757', help_text='Cor do marcador na tela Roteiro, pra confirmação visual.', max_length=7)),
                ('builtin', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaveis_roteiro', to='crm.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='variavel_roteiro',
            field=models.ForeignKey(blank=True, help_text='Opcional: guarda a resposta desta pergunta pra reusar como placeholder em outro texto do roteiro. Fixo nas 3 obrigatórias, opcional (via checkbox) nas demais.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='crm.variavelroteiro'),
        ),
        migrations.AddConstraint(
            model_name='variavelroteiro',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_variavelroteiro_name'),
        ),
        migrations.AddConstraint(
            model_name='variavelroteiro',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_company_variavelroteiro_slug'),
        ),
    ]
