# Generated by Django 5.2.17 on 2026-10-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_seed_variaveis_roteiro_builtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='desfecho_pendente',
            field=models.CharField(blank=True, choices=[('encerrado', 'Encerrado'), ('comprometido', 'Comprometido'), ('falha', 'Falha durante o atendimento')], help_text="Desfecho escolhido ao arrastar pra 'Despacho', mas ainda NÃO definitivo -- só vira Lead.desfecho (e some do Kanban) quando o owner clica 'Enviar Despachos' (services.enviar_despachos).", max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='etapa_atendimento',
            field=models.CharField(blank=True, choices=[('espera', 'Atendimentos em espera'), ('negociacao', 'Em negociação'), ('despacho', 'Despacho')], help_text="Coluna do Kanban pós-classificação em que um atendente já é owner. Vazio = ainda em 'Qualificados' (bot_closed, sem owner). Ver services.reivindicar_lead/mover_para_negociacao/preparar_despacho/liberar_lead.", max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='desfecho',
            field=models.CharField(blank=True, choices=[('encerrado', 'Encerrado'), ('comprometido', 'Comprometido'), ('falha', 'Falha durante o atendimento')], help_text='Só setado ao despachar um atendimento humano -- definitivo (ver services.enviar_despachos). Lead some do Kanban quando preenchido.', max_length=20),
        ),
    ]
