# Generated by Django 5.2.17 on 2026-10-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_etapa_atendimento_desfecho_pendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='origem_manual',
            field=models.BooleanField(default=False, help_text='Lead cadastrado manualmente por um atendente na tela Atendimento Humano (ver services.criar_lead_manual) -- nunca passou pelo funil do agente, não aparece no Kanban de Leads, só entra nas contagens do Dashboard.'),
        ),
    ]
