# Generated by Django 5.2.17 on 2026-10-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_lead_origem_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='agente_conversacional',
            field=models.BooleanField(default=True, help_text="Marcado: o agente envia o texto de apresentação e pode conversar livremente sobre a empresa (fallback 'empresa') enquanto aguarda o lead entrar no funil. Desmarcado: o agente vai direto pro funil de triagem com um texto inicial próprio, só esperando qualquer resposta do lead para avançar -- sem conversa livre sobre a empresa nesse meio-tempo. Configurado na tela Roteiro, aba 'Opções do Agente'."),
        ),
    ]
