# Generated by Django 5.2.17 on 2026-10-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_company_agente_conversacional'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='unique_company_contact',
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('desfecho', '')), fields=('company', 'contact'), name='unique_company_contact_ativo'),
        ),
    ]
