# Generated by Django 5.2.17 on 2026-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_event_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mensagens_audio',
            field=models.BooleanField(default=False, help_text='O agente envia todas as mensagens como áudio (TTS automático; perguntas com gravação própria usam a gravação). Só vale com allow_transcription ligado pelo Admin -- ver Company.audio_ativo.'),
        ),
        migrations.AddField(
            model_name='company',
            name='voz_tts',
            field=models.CharField(choices=[('pt-BR-FranciscaNeural', 'Francisca (feminina)'), ('pt-BR-AntonioNeural', 'Antonio (masculina)'), ('pt-BR-ThalitaMultilingualNeural', 'Thalita (feminina, multilíngue)')], default='pt-BR-FranciscaNeural', max_length=60),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_gravado',
            field=models.FileField(blank=True, help_text="Gravação própria desta pergunta (OGG/Opus mono 48k, convertida no upload). Com 'Mensagens via áudio' ligado, substitui o TTS automático.", upload_to='roteiro_audio/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_asset',
            field=models.CharField(blank=True, help_text='Obsoleto (não usado): substituído por audio_gravado.', max_length=250),
        ),
    ]
