# Generated by Django 5.2.17 on 2026-10-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_mensagens_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perguntas_spin', to='crm.area'),
        ),
        migrations.AddField(
            model_name='question',
            name='etapa_spin',
            field=models.CharField(blank=True, choices=[('', '—'), ('situacao', 'Situação'), ('problema', 'Problema'), ('implicacao', 'Implicação'), ('necessidade', 'Necessidade')], default='', max_length=12),
        ),
    ]
