# Generated by Django 5.2.17 on 2026-10-05 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_question_area_spin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='desfecho',
            field=models.CharField(blank=True, choices=[('encerrado', 'Encerrado'), ('comprometido', 'Comprometido'), ('falha', 'Falha durante o atendimento'), ('desqualificado', 'Desqualificado na triagem'), ('bloqueado', 'Bloqueado')], help_text='Definitivo: setado ao despachar (services.enviar_despachos) ou automaticamente ao classificar como Desqualificado/Desconfiado. Lead some do Kanban quando preenchido.', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='desfecho_pendente',
            field=models.CharField(blank=True, choices=[('encerrado', 'Encerrado'), ('comprometido', 'Comprometido'), ('falha', 'Falha durante o atendimento'), ('desqualificado', 'Desqualificado na triagem'), ('bloqueado', 'Bloqueado')], help_text="Desfecho escolhido ao arrastar pra 'Despacho', mas ainda NÃO definitivo -- só vira Lead.desfecho (e some do Kanban) quando o owner clica 'Enviar Despachos' (services.enviar_despachos).", max_length=20),
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(help_text='E.164 normalizado (+55...).', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adicionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to='crm.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'contact'), name='unique_company_blacklist_contact')],
            },
        ),
    ]
