# Generated by Django 5.2.18 on 2026-10-06 22:56

from django.db import migrations, models


def seed_necessidade_humana(apps, schema_editor):
    Company = apps.get_model("crm", "Company")
    Question = apps.get_model("crm", "Question")
    database = schema_editor.connection.alias
    for company_id in Company.objects.using(database).values_list("pk", flat=True).iterator():
        question, _ = Question.objects.using(database).get_or_create(
            company_id=company_id, question_id="necessidade_humana",
            defaults={"text": "Entendido. Vou encaminhar seu pedido para um atendente humano."},
        )
        # Preserva um texto eventualmente já cadastrado pela empresa.
        question.obrigatoria = True
        question.variavel_id = None
        question.variavel_roteiro_id = None
        question.area_id = None
        question.etapa_spin = ""
        question.save(using=database, update_fields=["obrigatoria", "variavel", "variavel_roteiro", "area", "etapa_spin"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_demanda_pedido_humano'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='variaveis_obrigatorias',
            field=models.ManyToManyField(blank=True, help_text='Variáveis que devem constar no texto de Necessidade humana e ter valor para a mensagem ser enviada.', related_name='mensagens_obrigatorias', to='crm.variavelroteiro'),
        ),
        migrations.RunPython(seed_necessidade_humana, migrations.RunPython.noop),
    ]
