# Generated by Django 5.2.18 on 2026-10-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_necessidade_humana'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pedido_humano_pendente',
            field=models.BooleanField(default=False, help_text='Cliente pediu humano, mas o agente ainda está coletando as variáveis mínimas obrigatórias.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='variaveis_obrigatorias',
            field=models.ManyToManyField(blank=True, help_text='Dados que o cliente deve informar antes de o agente encaminhar o lead para atendimento humano.', related_name='mensagens_obrigatorias', to='crm.variavelroteiro'),
        ),
    ]
