# Generated by Django 5.2.18 on 2026-10-07 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_coleta_minima_humano'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='etapa_inicial',
            field=models.BooleanField(default=False, help_text='Iniciar diretamente na SPIN selecionada e enviar somente suas perguntas.'),
        ),
        migrations.AddField(
            model_name='company',
            name='spin_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_inicio_spin', to='crm.area'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Nome definido pelo contato no WhatsApp; fallback ao concluir a qualificação.', max_length=160),
        ),
        migrations.AddField(
            model_name='question',
            name='habilitada',
            field=models.BooleanField(default=True, help_text='Permite ao agente enviar este texto fora do fluxo.'),
        ),
    ]
