# Generated by Django 5.2.18 on 2026-10-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_company_etapa_inicial_company_spin_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='envio_obrigatorio',
            field=models.BooleanField(default=False, help_text='Pergunta SPIN que deve ser enviada mesmo quando os dados necessários à classificação já foram capturados.'),
        ),
    ]
