# Generated by Django 5.2.18 on 2026-10-08 17:51

from django.db import migrations, models


TEXTOS = {"especial_acompanhamento": "Entendido! Já avisei a nossa equipe sobre o acompanhamento do seu processo. Em breve alguém entrará em contato."}


def seed_textos_especiais(apps, schema_editor):
    """Texto obrigatório fora do fluxo de cada situação especial, para as empresas que já existem."""
    Company = apps.get_model("crm", "Company")
    Question = apps.get_model("crm", "Question")
    database = schema_editor.connection.alias
    for company_id in Company.objects.using(database).values_list("pk", flat=True).iterator():
        for question_id, texto in TEXTOS.items():
            Question.objects.using(database).get_or_create(
                company_id=company_id, question_id=question_id,
                defaults={"text": texto, "obrigatoria": True, "variavel": None, "variavel_roteiro": None},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_question_envio_obrigatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='situacao_especial',
            field=models.CharField(blank=True, choices=[('acompanhamento', 'Acompanhamento de processo')], default='', help_text='Lead fora do fluxo de leads novos (ex.: acompanhamento de processo). Sem temperatura e fora do Kanban; aparece em Outras situações.', max_length=30),
        ),
        migrations.RunPython(seed_textos_especiais, migrations.RunPython.noop),
    ]
