# Generated by Django 5.2.18 on 2026-10-08 18:16

import django.db.models.deletion
from django.db import migrations, models


def backfill_novas(apps, schema_editor):
    """Histórico: novas leads por dia a partir dos leads que ainda existem (os já apagados não
    podem ser recuperados). Cadastros manuais ficam de fora, como na contagem em tempo real."""
    from collections import Counter
    from django.utils import timezone
    Lead = apps.get_model("crm", "Lead")
    ContagemDiaria = apps.get_model("crm", "ContagemDiaria")
    database = schema_editor.connection.alias
    contagem = Counter()
    for company_id, created_at in Lead.objects.using(database).filter(origem_manual=False).values_list("company_id", "created_at").iterator():
        contagem[(company_id, timezone.localtime(created_at).date())] += 1
    ContagemDiaria.objects.using(database).bulk_create(
        [ContagemDiaria(company_id=c, data=d, novas=n) for (c, d), n in contagem.items()]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_situacao_especial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContagemDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('novas', models.PositiveIntegerField(default=0)),
                ('nao_prosseguiram', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contagens_diarias', to='crm.company')),
            ],
            options={
                'ordering': ['-data'],
                'constraints': [models.UniqueConstraint(fields=('company', 'data'), name='unique_contagem_company_data')],
            },
        ),
        migrations.RunPython(backfill_novas, migrations.RunPython.noop),
    ]
