# Generated by Django 5.2.18 on 2026-10-08 18:23

from django.db import migrations, models


def renomear(apps, schema_editor, de="Remarketing", para="Frio"):
    """Temperatura "Remarketing" passa a se chamar "Frio" (campo do lead e detalhe do cálculo de urgência)."""
    Lead = apps.get_model("crm", "Lead")
    database = schema_editor.connection.alias
    Lead.objects.using(database).filter(temperature=de).update(temperature=para)
    for lead in Lead.objects.using(database).filter(urgencia_detalhe__temperatura_calculada=de).iterator():
        lead.urgencia_detalhe = {**lead.urgencia_detalhe, "temperatura_calculada": para}
        lead.save(using=database, update_fields=["urgencia_detalhe"])


def desfazer(apps, schema_editor):
    renomear(apps, schema_editor, de="Frio", para="Remarketing")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_contagem_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='temperature',
            field=models.CharField(blank=True, choices=[('Qualificado', 'Qualificado'), ('Quente', 'Quente'), ('Desconfiado', 'Desconfiado'), ('Frio', 'Frio'), ('Desqualificado', 'Desqualificado')], max_length=20),
        ),
        migrations.RunPython(renomear, desfazer),
    ]
