# Generated by Django 5.2.18 on 2026-10-09 13:23

from django.db import migrations, models


def copiar_spin_inicial(apps, schema_editor):
    """Cada empresa com Etapa Inicial passa a ter a SPIN que já usava como única habilitada."""
    Company = apps.get_model("crm", "Company")
    database = schema_editor.connection.alias
    for company in Company.objects.using(database).exclude(spin_inicial__isnull=True).iterator():
        company.spins_iniciais.add(company.spin_inicial_id)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_temperatura_frio'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='mensagem_campanha',
            field=models.TextField(blank=True, help_text='Etapa Inicial com várias SPINs: texto fixo que a campanha faz o cliente enviar para esta área (ex.: "Possuo descontos indevidos no meu benefício do INSS"). Ajuda o agente a reconhecer a área.', max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='spins_iniciais',
            field=models.ManyToManyField(blank=True, help_text='Etapa Inicial: SPINs que o cliente pode acessar. Com mais de uma, o agente escolhe pela mensagem inicial (campanha).', related_name='empresas_spins_iniciais', to='crm.area'),
        ),
        migrations.RunPython(copiar_spin_inicial, migrations.RunPython.noop),
    ]
