# Generated by Django 5.2.18 on 2026-10-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_spins_iniciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='coletar_historico_conversa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='mensagem_cliente',
            field=models.TextField(blank=True, default=''),
        ),
    ]
