# Generated by Django 5.2.18 on 2026-10-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_historico_conversa'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='marca_cor_contraste',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='marca_cor_principal',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='marca_logo',
            field=models.ImageField(blank=True, upload_to='marcas/'),
        ),
        migrations.AddField(
            model_name='company',
            name='marca_nome',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
