# Generated by Django 5.2.18 on 2026-10-10 01:36

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_lembrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='classificacao_cortes',
            field=models.JSONField(blank=True, default=crm.models.default_cortes_classificacao, help_text='4 notas (0-10, crescentes) onde terminam Desqualificado, Desconfiado, Frio e Qualificado; a partir da última é Quente. Padrão [3,5,7,9]; ver services.faixas_da_empresa.'),
        ),
        migrations.AddField(
            model_name='company',
            name='classificacao_regra',
            field=models.TextField(blank=True, default='', help_text='Critério em texto que o agente lê antes de dar as notas (tela Roteiro, aba Classificações). A temperatura final continua sendo calculada pelo CRM.', max_length=1500),
        ),
    ]
