# Generated by Django 5.2.18 on 2026-10-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_classificacao_regra_cortes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='despachado_pela_empresa',
            field=models.BooleanField(default=False, help_text='Acompanhamento de Outras situações despachado pela conta Empresa sem responsável: no lugar do responsável o Dashboard mostra "Despachado pela Empresa".'),
        ),
    ]
