# Generated by Django 5.2.18 on 2026-10-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_despachado_pela_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='classificacao_kanban_a_partir_de',
            field=models.PositiveSmallIntegerField(default=2, help_text='Índice (0 Desqualificado ... 4 Quente) da primeira classificação que vai para o Kanban de classificados; as anteriores concluem sozinhas e ficam fora dele. Padrão 2 (Frio em diante).'),
        ),
    ]
