# Generated by Django 5.2.18 on 2026-10-10 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def valores_iniciais(apps, schema_editor):
    Preco = apps.get_model("crm", "PrecoCobranca")
    from datetime import date
    for item, valor in (("implantacao", "5900"), ("base", "890"), ("empresa_adicional", "890"), ("agente_adicional", "400"), ("piloto", "2900")):
        Preco.objects.get_or_create(item=item, vigente_desde=date(2026, 1, 1), defaults={"valor": valor, "escopo": "novos", "nota": "Valor inicial"})


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_kanban_a_partir_de'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='em_teste',
            field=models.BooleanField(default=False, help_text='Empresa em fase de teste (piloto): cobra o valor do piloto em vez da mensalidade (Painel Admin, Cobranças).'),
        ),
        migrations.AddField(
            model_name='company',
            name='teste_convertido_em',
            field=models.DateField(blank=True, help_text='Dia em que o teste virou contrato.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='teste_dias',
            field=models.PositiveSmallIntegerField(default=30, help_text='Duração do teste em dias (cresce com as prorrogações).'),
        ),
        migrations.AddField(
            model_name='company',
            name='teste_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PrecoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('implantacao', 'Implantação inicial'), ('base', 'Conta de empresa (plano base)'), ('empresa_adicional', 'Empresa adicional'), ('agente_adicional', 'Agente adicional'), ('piloto', 'Piloto (empresa em teste)')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField()),
                ('escopo', models.CharField(choices=[('novos', 'Novos contratos'), ('reajuste', 'No próximo reajuste de cada contrato'), ('todos', 'Todos os contratos a partir da vigência'), ('escolher', 'Gestores escolhidos')], default='novos', max_length=12)),
                ('nota', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vigente_desde', '-id'],
                'indexes': [models.Index(fields=['item', '-vigente_desde'], name='crm_precoco_item_9e470d_idx')],
            },
        ),
        migrations.RunPython(valores_iniciais, migrations.RunPython.noop),
    ]
