# Generated by Django 5.2.18 on 2026-10-10 05:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def regra_inicial(apps, schema_editor):
    Regra = apps.get_model("crm", "RegraCobranca")
    if not Regra.objects.exists():
        Regra.objects.create(descontos=[[12, 5], [24, 10], [36, 12]])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_cobrancas_precos_e_teste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prorata_ativo', models.BooleanField(default=True)),
                ('descontos', models.JSONField(blank=True, default=list, help_text='Lista [[meses_de_contrato, percentual], ...]; vale o maior percentual cujo prazo já passou. Ex.: [[12, 5], [24, 10]].')),
                ('abater_piloto', models.BooleanField(default=True)),
                ('abatimento_pct', models.PositiveSmallIntegerField(default=100)),
                ('indice_padrao', models.CharField(default='IPCA', max_length=20)),
                ('alerta_reajuste_dias', models.PositiveSmallIntegerField(default=60)),
                ('faixa_atraso_curta', models.PositiveSmallIntegerField(default=5)),
                ('faixa_atraso_media', models.PositiveSmallIntegerField(default=15)),
                ('aviso_desligamento_dias', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, default='', help_text='E-mail de contato e de cobrança.', max_length=254)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('forma_pagamento', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao', 'Cartão'), ('outro', 'Outro')], default='pix', max_length=10)),
                ('contrato_inicio', models.DateField(blank=True, help_text='Início do contrato: base do pro-rata, do desconto por tempo e do reajuste anual.', null=True)),
                ('indice_reajuste', models.CharField(default='IPCA', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Conta Empresa (login) do gestor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensalidade', 'Mensalidade'), ('piloto', 'Piloto'), ('implantacao', 'Implantação')], default='mensalidade', max_length=12)),
                ('referencia', models.DateField(help_text='Primeiro dia do mês de referência.')),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('linhas', models.JSONField(blank=True, default=list, help_text='[{descricao, valor, empresa, agente}] (descontos entram com valor negativo).')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='crm.gestor')),
            ],
            options={
                'ordering': ['-referencia', '-id'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='gestor',
            field=models.ForeignKey(blank=True, help_text='Cliente que paga por esta empresa (Painel Admin, Gestores).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='crm.gestor'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao', 'Cartão'), ('outro', 'Outro')], default='pix', max_length=10)),
                ('comprovante', models.CharField(blank=True, default='', help_text='Nome do arquivo ou link do comprovante.', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='crm.cobranca')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.UniqueConstraint(fields=('gestor', 'tipo', 'referencia'), name='unique_cobranca_gestor_tipo_mes'),
        ),
        migrations.RunPython(regra_inicial, migrations.RunPython.noop),
    ]
