# Generated by Django 5.2.18 on 2026-10-10 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def config_inicial(apps, schema_editor):
    Config = apps.get_model("crm", "ConfigNotificacao")
    if not Config.objects.exists():
        Config.objects.create(teste_dias_avisos=[7, 3, 1, 0], chave_dias_avisos=[30, 7])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_gestores_cobrancas_pagamentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(blank=True, default='', help_text='E-mail remetente; vazio = DEFAULT_FROM_EMAIL do servidor.', max_length=160)),
                ('cc', models.CharField(blank=True, default='', help_text='Cópia (financeiro) nos e-mails de cobrança.', max_length=160)),
                ('lembrete_cobranca_ativo', models.BooleanField(default=True)),
                ('lembrete_dias_antes', models.PositiveSmallIntegerField(default=5)),
                ('teste_ativo', models.BooleanField(default=True)),
                ('teste_dias_avisos', models.JSONField(blank=True, default=list, help_text='Dias antes do fim do teste (0 = no dia). Ex.: [7, 3, 1, 0].')),
                ('atraso_f1', models.BooleanField(default=True)),
                ('atraso_f2', models.BooleanField(default=True)),
                ('atraso_f3', models.BooleanField(default=True)),
                ('chave_ativo', models.BooleanField(default=True)),
                ('chave_dias_avisos', models.JSONField(blank=True, default=list, help_text='Dias antes de a chave de API do agente expirar. Ex.: [30, 7].')),
                ('texto_cobranca', models.TextField(default='Olá, {gestor}! Sua mensalidade de {valor} vence em {vencimento}. Qualquer dúvida é só responder este e-mail.')),
                ('texto_teste', models.TextField(default='Olá, {gestor}! O teste de {empresa} termina em {fim_do_teste}. Se quiser continuar, é só confirmar por aqui: o valor do piloto é abatido da implantação.')),
                ('texto_atraso', models.TextField(default='Olá, {gestor}! Não identificamos o pagamento de {valor}, vencido em {vencimento}. Se já pagou, envie o comprovante respondendo este e-mail.')),
                ('texto_desligamento', models.TextField(default='Olá, {gestor}! A cobrança de {valor}, vencida em {vencimento}, segue em aberto. Os agentes serão desligados em {dias_desligamento} dias se o pagamento não for regularizado.')),
                ('texto_chave', models.TextField(default='Olá, {gestor}! A chave de API do agente {agente} (empresa {empresa}) expira em {chave_expira_em}. Podemos gerar uma nova quando você preferir; é só responder este e-mail.')),
            ],
        ),
        migrations.AddField(
            model_name='gestor',
            name='openai_chave_final',
            field=models.CharField(blank=True, default='', help_text='Últimos caracteres da chave, só para conferência.', max_length=8),
        ),
        migrations.AddField(
            model_name='gestor',
            name='openai_limite_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limite de consumo mensal combinado, em R$.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gestor',
            name='openai_projeto',
            field=models.CharField(blank=True, default='', help_text='Nome do projeto da OpenAI do gestor (a chave em si fica no gateway de cada agente).', max_length=120),
        ),
        migrations.CreateModel(
            name='NotificacaoEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestor_nome', models.CharField(blank=True, default='', max_length=160)),
                ('para', models.CharField(blank=True, default='', max_length=200)),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('cobranca', 'Lembrete de cobrança'), ('teste', 'Fim do teste'), ('atraso', 'Cobrança em atraso'), ('desligamento', 'Aviso de desligamento'), ('chave', 'Chave de API')], default='manual', max_length=14)),
                ('assunto', models.CharField(max_length=250)),
                ('corpo', models.TextField(blank=True, default='')),
                ('chave', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('estado', models.CharField(default='enviado', max_length=10)),
                ('erro', models.CharField(blank=True, default='', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='crm.gestor')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.RunPython(config_inicial, migrations.RunPython.noop),
    ]
