# Generated by Django 5.2.18 on 2026-10-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_notificacoes_e_chave_openai'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='openai_modo',
            field=models.CharField(choices=[('chave', 'Chave de API do gestor'), ('plano', 'Plano gerido pela Axioma')], default='chave', help_text='chave = o gestor paga o consumo pela chave dele; plano = agentes no plano (ex.: ChatGPT Pro) gerido pela Axioma, com limite.', max_length=6),
        ),
        migrations.AddField(
            model_name='notificacaoenviada',
            name='anexos',
            field=models.JSONField(blank=True, default=list, help_text='Nomes dos arquivos enviados em anexo.'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='comprovante_arquivo',
            field=models.FileField(blank=True, help_text='Comprovante anexado (PDF ou imagem).', upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante',
            field=models.CharField(blank=True, default='', help_text='Link ou referência do comprovante (quando não há arquivo).', max_length=300),
        ),
    ]
