# Generated by Django 5.2.18 on 2026-10-10 16:59

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_area_fora_de_escopo_fixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante_arquivo',
            field=models.FileField(blank=True, help_text='Comprovante anexado (PDF ou imagem), fora do /media/ público.', storage=crm.models.armazenamento_privado, upload_to=crm.models.caminho_comprovante),
        ),
    ]
